export const Translations = {
  en: {
    skip: "Skip",
  next: "Next",
  getStarted: "Get Started",
  welcome: "Welcome to MedConnect",
  consultDoctors: "Consult Specialists",
  chatInstead: "Instant Chat Support",
  payMobile: "Secure Wallet Payments",
    welcomeBack: "Welcome Back",
    loginSubtitle: "Log in to access your healthcare dashboard.",
    phoneOrEmail: "Phone Number or Email",
    password: "Password",
    forgotPassword: "Forgot Password?",
    logIn: "Log In",
    or: "OR",
    continueGoogle: "Continue with Google",
    noAccount: "Don't have an account?",
    signUpNow: "Sign up now",
    
    // Patient Tabs & Core Layout Elements
    home: "Home",
    consults: "Consults",
    wallet: "Wallet",
    profile: "Profile",
    
    // Dashboard & Booking Flow
    feelingUnwell: "Feeling unwell?",
    checkSymptoms: "Check your symptoms with our AI assistant in seconds.",
    checkNow: "Check Now",
    recommendedDoctors: "Recommended Doctors",
    seeAll: "See All",
    bookNow: "Book Now",
    addToCart: "Add to Cart",
    
    // Payment Page
    completePayment: "Complete Your Payment",
    paymentMethod: "Payment Method / Njia ya Malipo",
    mobileNumber: "Mobile Number / Namba ya Simu",
    payNow: "Pay Now / Lipa Sasa",
    totalAmount: "Total Amount",

   

    // Modals & Forms
    storedConsults: "My Scheduled Consultations",
    noConsults: "No scheduled consultations active at this time.",
    modifyNotes: "Modify Notes",
    cancelAppt: "Cancel Appt",
    updateSymptomsLog: "Update Symptoms Log",
    confirmUpdate: "Confirm Update",
    closePanel: "Close Panel",
    selectCommMode: "Select Communication Mode",
    commModeDesc: "Choose your preferred secure clinical contact channel:",
    textChat: "Interactive Text Chat",
    chatPending: "Not created yet — Environment Setup pending",
    videoConsult: "Live Video Consultation",
    videoActive: "Screen is fully functional & deployed",
    allProviders: "All Registered Providers",
    allProvidersDesc: "Sorted matches filtered by your diagnosed medical problems:",
    select: "Select",

    // Prescription / Intake Form
    intakeTitle: "Consultant Clinical Intake Form",
    intakeDesc: "Write out your health notes, chronic updates, or prescription logs below:",
    selectTarget: "Select Target Consultant",
    detailedLog: "Detailed Information Log",
    placeholderIntake: "Provide a breakdown of active symptoms, long-term prescription details, or queries for your provider...",
    transmitLog: "Transmit Log",


    addToCart: "Add to Cart 🛒",
  bookNow: "Book Now",
  selectDate: "Select Date:",
  availableSlots: "Available Slots:",
  cartSuccessTitle: "Added to Cart!",
  cartSuccessMessage: "Saved: \nDoctor: {doc}\nType: {type}\nDate: {date}\nSlot: {slot}\nFee: {fee}",

  yourCart: "Your Cart",
  reviewBookings: "Review your medical bookings",
  changeSlot: "Change time slot",
  browseServices: "Browse Services",
  laboratoryNeed: "Need to add laboratory tests or pharmacy items?",
  orderSummary: "ORDER SUMMARY",
  subtotal: "Subtotal",
  serviceFee: "Service Fee",
  total: "Total",
  proceedToCheckout: "Proceed to Checkout",
  continueBooking: "Continue Booking",
  checkout: "Checkout",
  bookingSummary: "Booking Summary",
  practitioner: "PRACTITIONER",
  totalPayable: "TOTAL PAYABLE",
  consultationType: "Consultation Type",
  appointmentDate: "Appointment Date",
  appointmentTime: "Appointment Time",
  paymentMethod: "Payment Method",
  termsNotice: "By clicking \"Confirm & Pay\", you agree to our Telehealth Terms of Service.",
  confirmAndPay: "Confirm & Pay",
  bookingConfirmed: "Booking Confirmed!",
  successSubtitle: "Your medical consultation has been successfully scheduled. We've notified both you and your doctor via SMS and Email.",
  appointmentId: "APPOINTMENT ID",
  status: "STATUS",
  confirmed: "Confirmed",
  payment: "PAYMENT",
  paid: "Paid",
  goToMyConsultations: "Go to My Consultations",
  backToHome: "Back to Home",
  readyConsultation: "Ready for Consultation",
  preparationChecklist: "PREPARATION CHECKLIST",
  checkStableNet: "Internet connection stable",
  checkHardware: "Microphone & Camera tested",
  checkQuiet: "Quiet environment secured",
  startsIn: "STARTS IN",
  minutes: "Minutes",
  seconds: "Seconds",
  startConsultationBtn: "Start Consultation",
  doctorJoinNotice: "The doctor will join the room shortly.",
  chat: "Chat",
  voiceCall: "Voice Call",
  videoCall: "Video Call",
  documents: "Documents",
  uploadNew: "+ Upload New"
},
sw: {
  },
  sw: {


    skip: "Ruka",
  next: "Mbele",
  getStarted: "Anza Sasa",
  welcome: "Karibu MedConnect",
  consultDoctors: "Ongea na Madaktari",
  chatInstead: "Soga la Papo Hapo",
    welcomeBack: "Karibu Tena",
    loginSubtitle: "Ingia ili ufikie ukurasa wako wa matibabu.",
    phoneOrEmail: "Namba ya Simu au Barua Pepe",
    password: "Nywila",
    forgotPassword: "Umesahau Nywila?",
    logIn: "Ingia Sasa",
    or: "AU",
    continueGoogle: "Endelea na Google",
    noAccount: "Huna akaunti bado?",
    signUpNow: "Jisajili sasa",
    
    // Patient Tabs & Core Layout Elements
    home: "Nyumbani",
    consults: "Ushauri",
    wallet: "Mkoba",
    profile: "Wasifu",
    
    // Dashboard & Booking Flow
    feelingUnwell: "Unajisikia vibaya?",
    checkSymptoms: "Kagua dalili zako na msaidizi wetu wa AI kwa sekunde.",
    checkNow: "Kagua Sasa",
    recommendedDoctors: "Madaktari Waliopendekezwa",
    seeAll: "Ona Zote",
    bookNow: "Weka Nafasi",
    addToCart: "Weka Kwenye Kikapu",
    
    // Modals & Forms
    storedConsults: "Miadi Yangu Iliyoratibiwa",
    noConsults: "Hakuna miadi yoyote iliyopangwa kwa sasa.",
    modifyNotes: "Badili Maelezo",
    cancelAppt: "Ghairi Miadi",
    updateSymptomsLog: "Sasisha Dalili Zako",
    confirmUpdate: "Thibitisha Mabadiliko",
    closePanel: "Funga Dirisha",
    selectCommMode: "Chagua Njia ya Mawasiliano",
    commModeDesc: "Chagua njia salama unayopendelea kuwasiliana na kliniki:",
    textChat: "Soga ya Maandishi",
    chatPending: "Haijakamilika — Matengenezo ya mfumo yanaendelea",
    videoConsult: "Ushauri wa Video ya Moja kwa Moja",
    videoActive: "Inafanya kazi kikamilifu na imesakinishwa",
    allProviders: "Watoa Huduma Wote",
    allProvidersDesc: "Orodha iliyochujwa kulingana na matatizo ya kiafya yanayokukabili:",
    select: "Chagua",

    // Prescription / Intake Form
    intakeTitle: "Fomu ya Maelezo ya Awali ya Matibabu",
    intakeDesc: "Andika maelezo ya afya yako, mabadiliko ya magonjwa ya muda mrefu, au rekodi za dawa hapa chini:",
    selectTarget: "Chagua Daktari Mlengwa",
    detailedLog: "Maelezo ya Kina ya Dalili",
    placeholderIntake: "Toa mchanganuo wa dalili zako za sasa, maelezo ya dawa za muda mrefu, au maswali kwa mtoa huduma wako...",
    transmitLog: "Tuma Taarifa",

    
    // Payment Page
    completePayment: "Kamilisha Malipo Yako",
    paymentMethod: "Njia ya Malipo / Payment Method",
    mobileNumber: "Namba ya Simu / Mobile Number",
    payNow: "Lipa Sasa / Pay Now",
    totalAmount: "Jumla Kuu",
    addToCart: "Weka Kwenye Kikapu 🛒",
  bookNow: "Weka Miadi",
  selectDate: "Chagua Tarehe:",
  availableSlots: "Nafasi Zilizopo:",
  cartSuccessTitle: "Imewekwa Kwenye Kikapu!",
  cartSuccessMessage: "Imehifadhiwa: \nDaktari: {doc}\nAina: {type}\nTarehe: {date}\nMuda: {slot}\nGharama: {fee}",
  yourCart: "Kikapu Chako",
  reviewBookings: "Hakiki miadi yako ya matibabu",
  changeSlot: "Badilisha muda uliochagua",
  browseServices: "Angalia Huduma Nyingine",
  laboratoryNeed: "Je, unahitaji kuongeza vipimo vya maabara au dawa?",
  orderSummary: "MUHTASARI WA GHARAMA",
  subtotal: "Nusu Jumla",
  serviceFee: "Gharama ya Huduma",
  total: "Jumla Kuu",
  proceedToCheckout: "Endelea Lipia Miadi",
  continueBooking: "Endelea Kuchagua Miadi",
  checkout: "Malipo",
  bookingSummary: "Muhtasari wa Kuhifadhi",
  practitioner: "DAKTARI",
  totalPayable: "JUMLA YA MALIPO",
  consultationType: "Aina ya Ushauri",
  appointmentDate: "Tarehe ya Miadi",
  appointmentTime: "Muda wa Miadi",
  paymentMethod: "Njia ya Malipo",
  termsNotice: "Kwa kubonyeza \"Thibitisha & Lipa\", unakubaliana na Masharti yetu ya Huduma ya Telehealth.",
  confirmAndPay: "Thibitisha & Lipa",
  bookingConfirmed: "Uwekaji Nafasi Umethibitishwa!",
  successSubtitle: "Ushauri wako wa matibabu umeratibiwa kikamilifu. Tumetuma taarifa kwako na kwa daktari wako kwa njia ya SMS na Barua Pepe.",
  appointmentId: "KITAMBULISHO CHA MIADI",
  status: "HALI YA MIADI",
  confirmed: "Imethibitishwa",
  payment: "MALIPO",
  paid: "Imelipwa",
  goToMyConsultations: "Nenda kwenye Miadi Yangu",
  backToHome: "Rudi Nyumbani",
  readyConsultation: "Tayari kwa Ushauri wa Matibabu",
  preparationChecklist: "ORODHA YA MATAYARISHO",
  checkStableNet: "Uunganisho wa mtandao umeridhisha",
  checkHardware: "Maikrofoni na Kamera zimejaribiwa",
  checkQuiet: "Mazingira tulivu yamehakikishwa",
  startsIn: "INAANZA BAADA YA",
  minutes: "Dakika",
  seconds: "Sekunde",
  startConsultationBtn: "Anza Ushauri Sasa",
  doctorJoinNotice: "Daktari ataingia kwenye chumba cha mazungumzo hivi punde.",
  chat: "Soga",
  voiceCall: "Simu ya Sauti",
  videoCall: "Simu ya Video",
  documents: "Nyaraka",
  uploadNew: "+ Pakia Mpya",
  }
};